name: Run checkstyle
# Checkstyle 13+ requires Java 21+.
on: [push, pull_request]
permissions: {}
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: zulu
          java-version: 24
      - run: mvn checkstyle:check -B
