name: Run tests
on: [push, pull_request]
permissions: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        distribution: ['zulu']
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [ 17, 21, 24 ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - run: mvn test -B
      # This is after the test run to work around
      # https://issues.apache.org/jira/projects/MJAVADOC/issues/MJAVADOC-736
      - run: mvn javadoc:javadoc
