name: Run tests
on: [push, pull_request]
permissions: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        distribution: ['zulu']
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [ 17, 21, 24 ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - run: mvn test -B
      # This is after the test run to work around
      # https://issues.apache.org/jira/projects/MJAVADOC/issues/MJAVADOC-736
      - run: mvn javadoc:javadoc
